# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone project
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: Build and Test
      run: |
        ./gradlew check
      
    - name: Gradle Wrapper Cache
      uses: actions/cache@v2.0.0
      with:
        key: gradle-wrapper
        path: ~/.gradle/wrapper
        
    - name: Dependencies Cache
      uses: actions/cache@v2.0.0
      with:
        key: dependencies
        path: ~/.m2/repository
